// Code generated by MockGen. DO NOT EDIT.
// Source: backend/interfaces.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	backend "github.com/abhipray-cpu/niyantrak/backend"
	gomock "github.com/golang/mock/gomock"
)

// MockBackend is a mock of Backend interface.
type MockBackend struct {
	ctrl     *gomock.Controller
	recorder *MockBackendMockRecorder
}

// MockBackendMockRecorder is the mock recorder for MockBackend.
type MockBackendMockRecorder struct {
	mock *MockBackend
}

// NewMockBackend creates a new mock instance.
func NewMockBackend(ctrl *gomock.Controller) *MockBackend {
	mock := &MockBackend{ctrl: ctrl}
	mock.recorder = &MockBackendMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBackend) EXPECT() *MockBackendMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockBackend) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockBackendMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockBackend)(nil).Close))
}

// Delete mocks base method.
func (m *MockBackend) Delete(ctx context.Context, key string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, key)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockBackendMockRecorder) Delete(ctx, key interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockBackend)(nil).Delete), ctx, key)
}

// Get mocks base method.
func (m *MockBackend) Get(ctx context.Context, key string) (interface{}, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, key)
	ret0, _ := ret[0].(interface{})
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockBackendMockRecorder) Get(ctx, key interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockBackend)(nil).Get), ctx, key)
}

// IncrementAndGet mocks base method.
func (m *MockBackend) IncrementAndGet(ctx context.Context, key string, ttl time.Duration) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IncrementAndGet", ctx, key, ttl)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IncrementAndGet indicates an expected call of IncrementAndGet.
func (mr *MockBackendMockRecorder) IncrementAndGet(ctx, key, ttl interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncrementAndGet", reflect.TypeOf((*MockBackend)(nil).IncrementAndGet), ctx, key, ttl)
}

// Ping mocks base method.
func (m *MockBackend) Ping(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ping", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Ping indicates an expected call of Ping.
func (mr *MockBackendMockRecorder) Ping(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ping", reflect.TypeOf((*MockBackend)(nil).Ping), ctx)
}

// Set mocks base method.
func (m *MockBackend) Set(ctx context.Context, key string, state interface{}, ttl time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Set", ctx, key, state, ttl)
	ret0, _ := ret[0].(error)
	return ret0
}

// Set indicates an expected call of Set.
func (mr *MockBackendMockRecorder) Set(ctx, key, state, ttl interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Set", reflect.TypeOf((*MockBackend)(nil).Set), ctx, key, state, ttl)
}

// Type mocks base method.
func (m *MockBackend) Type() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Type")
	ret0, _ := ret[0].(string)
	return ret0
}

// Type indicates an expected call of Type.
func (mr *MockBackendMockRecorder) Type() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Type", reflect.TypeOf((*MockBackend)(nil).Type))
}

// MockMemoryBackend is a mock of MemoryBackend interface.
type MockMemoryBackend struct {
	ctrl     *gomock.Controller
	recorder *MockMemoryBackendMockRecorder
}

// MockMemoryBackendMockRecorder is the mock recorder for MockMemoryBackend.
type MockMemoryBackendMockRecorder struct {
	mock *MockMemoryBackend
}

// NewMockMemoryBackend creates a new mock instance.
func NewMockMemoryBackend(ctrl *gomock.Controller) *MockMemoryBackend {
	mock := &MockMemoryBackend{ctrl: ctrl}
	mock.recorder = &MockMemoryBackendMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMemoryBackend) EXPECT() *MockMemoryBackendMockRecorder {
	return m.recorder
}

// Clear mocks base method.
func (m *MockMemoryBackend) Clear(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Clear", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Clear indicates an expected call of Clear.
func (mr *MockMemoryBackendMockRecorder) Clear(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Clear", reflect.TypeOf((*MockMemoryBackend)(nil).Clear), ctx)
}

// Close mocks base method.
func (m *MockMemoryBackend) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockMemoryBackendMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockMemoryBackend)(nil).Close))
}

// Delete mocks base method.
func (m *MockMemoryBackend) Delete(ctx context.Context, key string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, key)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockMemoryBackendMockRecorder) Delete(ctx, key interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockMemoryBackend)(nil).Delete), ctx, key)
}

// Get mocks base method.
func (m *MockMemoryBackend) Get(ctx context.Context, key string) (interface{}, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, key)
	ret0, _ := ret[0].(interface{})
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockMemoryBackendMockRecorder) Get(ctx, key interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockMemoryBackend)(nil).Get), ctx, key)
}

// GetMemoryUsage mocks base method.
func (m *MockMemoryBackend) GetMemoryUsage(ctx context.Context) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMemoryUsage", ctx)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMemoryUsage indicates an expected call of GetMemoryUsage.
func (mr *MockMemoryBackendMockRecorder) GetMemoryUsage(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMemoryUsage", reflect.TypeOf((*MockMemoryBackend)(nil).GetMemoryUsage), ctx)
}

// GetSize mocks base method.
func (m *MockMemoryBackend) GetSize(ctx context.Context) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSize", ctx)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSize indicates an expected call of GetSize.
func (mr *MockMemoryBackendMockRecorder) GetSize(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSize", reflect.TypeOf((*MockMemoryBackend)(nil).GetSize), ctx)
}

// IncrementAndGet mocks base method.
func (m *MockMemoryBackend) IncrementAndGet(ctx context.Context, key string, ttl time.Duration) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IncrementAndGet", ctx, key, ttl)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IncrementAndGet indicates an expected call of IncrementAndGet.
func (mr *MockMemoryBackendMockRecorder) IncrementAndGet(ctx, key, ttl interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncrementAndGet", reflect.TypeOf((*MockMemoryBackend)(nil).IncrementAndGet), ctx, key, ttl)
}

// Ping mocks base method.
func (m *MockMemoryBackend) Ping(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ping", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Ping indicates an expected call of Ping.
func (mr *MockMemoryBackendMockRecorder) Ping(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ping", reflect.TypeOf((*MockMemoryBackend)(nil).Ping), ctx)
}

// Set mocks base method.
func (m *MockMemoryBackend) Set(ctx context.Context, key string, state interface{}, ttl time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Set", ctx, key, state, ttl)
	ret0, _ := ret[0].(error)
	return ret0
}

// Set indicates an expected call of Set.
func (mr *MockMemoryBackendMockRecorder) Set(ctx, key, state, ttl interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Set", reflect.TypeOf((*MockMemoryBackend)(nil).Set), ctx, key, state, ttl)
}

// SetMaxSize mocks base method.
func (m *MockMemoryBackend) SetMaxSize(ctx context.Context, maxSize int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetMaxSize", ctx, maxSize)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetMaxSize indicates an expected call of SetMaxSize.
func (mr *MockMemoryBackendMockRecorder) SetMaxSize(ctx, maxSize interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetMaxSize", reflect.TypeOf((*MockMemoryBackend)(nil).SetMaxSize), ctx, maxSize)
}

// Type mocks base method.
func (m *MockMemoryBackend) Type() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Type")
	ret0, _ := ret[0].(string)
	return ret0
}

// Type indicates an expected call of Type.
func (mr *MockMemoryBackendMockRecorder) Type() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Type", reflect.TypeOf((*MockMemoryBackend)(nil).Type))
}

// MockRedisBackend is a mock of RedisBackend interface.
type MockRedisBackend struct {
	ctrl     *gomock.Controller
	recorder *MockRedisBackendMockRecorder
}

// MockRedisBackendMockRecorder is the mock recorder for MockRedisBackend.
type MockRedisBackendMockRecorder struct {
	mock *MockRedisBackend
}

// NewMockRedisBackend creates a new mock instance.
func NewMockRedisBackend(ctrl *gomock.Controller) *MockRedisBackend {
	mock := &MockRedisBackend{ctrl: ctrl}
	mock.recorder = &MockRedisBackendMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRedisBackend) EXPECT() *MockRedisBackendMockRecorder {
	return m.recorder
}

// CheckCluster mocks base method.
func (m *MockRedisBackend) CheckCluster(ctx context.Context) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckCluster", ctx)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckCluster indicates an expected call of CheckCluster.
func (mr *MockRedisBackendMockRecorder) CheckCluster(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckCluster", reflect.TypeOf((*MockRedisBackend)(nil).CheckCluster), ctx)
}

// Close mocks base method.
func (m *MockRedisBackend) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockRedisBackendMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockRedisBackend)(nil).Close))
}

// Delete mocks base method.
func (m *MockRedisBackend) Delete(ctx context.Context, key string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, key)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockRedisBackendMockRecorder) Delete(ctx, key interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockRedisBackend)(nil).Delete), ctx, key)
}

// Flush mocks base method.
func (m *MockRedisBackend) Flush(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Flush", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Flush indicates an expected call of Flush.
func (mr *MockRedisBackendMockRecorder) Flush(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Flush", reflect.TypeOf((*MockRedisBackend)(nil).Flush), ctx)
}

// Get mocks base method.
func (m *MockRedisBackend) Get(ctx context.Context, key string) (interface{}, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, key)
	ret0, _ := ret[0].(interface{})
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockRedisBackendMockRecorder) Get(ctx, key interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockRedisBackend)(nil).Get), ctx, key)
}

// GetConnection mocks base method.
func (m *MockRedisBackend) GetConnection(ctx context.Context) *backend.ConnectionInfo {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetConnection", ctx)
	ret0, _ := ret[0].(*backend.ConnectionInfo)
	return ret0
}

// GetConnection indicates an expected call of GetConnection.
func (mr *MockRedisBackendMockRecorder) GetConnection(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetConnection", reflect.TypeOf((*MockRedisBackend)(nil).GetConnection), ctx)
}

// GetReplication mocks base method.
func (m *MockRedisBackend) GetReplication(ctx context.Context) *backend.ReplicationStatus {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetReplication", ctx)
	ret0, _ := ret[0].(*backend.ReplicationStatus)
	return ret0
}

// GetReplication indicates an expected call of GetReplication.
func (mr *MockRedisBackendMockRecorder) GetReplication(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetReplication", reflect.TypeOf((*MockRedisBackend)(nil).GetReplication), ctx)
}

// IncrementAndGet mocks base method.
func (m *MockRedisBackend) IncrementAndGet(ctx context.Context, key string, ttl time.Duration) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IncrementAndGet", ctx, key, ttl)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IncrementAndGet indicates an expected call of IncrementAndGet.
func (mr *MockRedisBackendMockRecorder) IncrementAndGet(ctx, key, ttl interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncrementAndGet", reflect.TypeOf((*MockRedisBackend)(nil).IncrementAndGet), ctx, key, ttl)
}

// Ping mocks base method.
func (m *MockRedisBackend) Ping(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ping", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Ping indicates an expected call of Ping.
func (mr *MockRedisBackendMockRecorder) Ping(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ping", reflect.TypeOf((*MockRedisBackend)(nil).Ping), ctx)
}

// Scan mocks base method.
func (m *MockRedisBackend) Scan(ctx context.Context, pattern string, count int) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Scan", ctx, pattern, count)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Scan indicates an expected call of Scan.
func (mr *MockRedisBackendMockRecorder) Scan(ctx, pattern, count interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Scan", reflect.TypeOf((*MockRedisBackend)(nil).Scan), ctx, pattern, count)
}

// Set mocks base method.
func (m *MockRedisBackend) Set(ctx context.Context, key string, state interface{}, ttl time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Set", ctx, key, state, ttl)
	ret0, _ := ret[0].(error)
	return ret0
}

// Set indicates an expected call of Set.
func (mr *MockRedisBackendMockRecorder) Set(ctx, key, state, ttl interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Set", reflect.TypeOf((*MockRedisBackend)(nil).Set), ctx, key, state, ttl)
}

// Type mocks base method.
func (m *MockRedisBackend) Type() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Type")
	ret0, _ := ret[0].(string)
	return ret0
}

// Type indicates an expected call of Type.
func (mr *MockRedisBackendMockRecorder) Type() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Type", reflect.TypeOf((*MockRedisBackend)(nil).Type))
}

// MockPostgreSQLBackend is a mock of PostgreSQLBackend interface.
type MockPostgreSQLBackend struct {
	ctrl     *gomock.Controller
	recorder *MockPostgreSQLBackendMockRecorder
}

// MockPostgreSQLBackendMockRecorder is the mock recorder for MockPostgreSQLBackend.
type MockPostgreSQLBackendMockRecorder struct {
	mock *MockPostgreSQLBackend
}

// NewMockPostgreSQLBackend creates a new mock instance.
func NewMockPostgreSQLBackend(ctrl *gomock.Controller) *MockPostgreSQLBackend {
	mock := &MockPostgreSQLBackend{ctrl: ctrl}
	mock.recorder = &MockPostgreSQLBackendMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPostgreSQLBackend) EXPECT() *MockPostgreSQLBackendMockRecorder {
	return m.recorder
}

// CleanupExpired mocks base method.
func (m *MockPostgreSQLBackend) CleanupExpired(ctx context.Context) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CleanupExpired", ctx)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CleanupExpired indicates an expected call of CleanupExpired.
func (mr *MockPostgreSQLBackendMockRecorder) CleanupExpired(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CleanupExpired", reflect.TypeOf((*MockPostgreSQLBackend)(nil).CleanupExpired), ctx)
}

// Close mocks base method.
func (m *MockPostgreSQLBackend) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockPostgreSQLBackendMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockPostgreSQLBackend)(nil).Close))
}

// CreateTable mocks base method.
func (m *MockPostgreSQLBackend) CreateTable(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTable", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateTable indicates an expected call of CreateTable.
func (mr *MockPostgreSQLBackendMockRecorder) CreateTable(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTable", reflect.TypeOf((*MockPostgreSQLBackend)(nil).CreateTable), ctx)
}

// Delete mocks base method.
func (m *MockPostgreSQLBackend) Delete(ctx context.Context, key string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, key)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockPostgreSQLBackendMockRecorder) Delete(ctx, key interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockPostgreSQLBackend)(nil).Delete), ctx, key)
}

// Get mocks base method.
func (m *MockPostgreSQLBackend) Get(ctx context.Context, key string) (interface{}, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, key)
	ret0, _ := ret[0].(interface{})
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockPostgreSQLBackendMockRecorder) Get(ctx, key interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockPostgreSQLBackend)(nil).Get), ctx, key)
}

// GetSchema mocks base method.
func (m *MockPostgreSQLBackend) GetSchema(ctx context.Context) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSchema", ctx)
	ret0, _ := ret[0].(string)
	return ret0
}

// GetSchema indicates an expected call of GetSchema.
func (mr *MockPostgreSQLBackendMockRecorder) GetSchema(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSchema", reflect.TypeOf((*MockPostgreSQLBackend)(nil).GetSchema), ctx)
}

// GetStats mocks base method.
func (m *MockPostgreSQLBackend) GetStats(ctx context.Context) *backend.DatabaseStats {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStats", ctx)
	ret0, _ := ret[0].(*backend.DatabaseStats)
	return ret0
}

// GetStats indicates an expected call of GetStats.
func (mr *MockPostgreSQLBackendMockRecorder) GetStats(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStats", reflect.TypeOf((*MockPostgreSQLBackend)(nil).GetStats), ctx)
}

// IncrementAndGet mocks base method.
func (m *MockPostgreSQLBackend) IncrementAndGet(ctx context.Context, key string, ttl time.Duration) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IncrementAndGet", ctx, key, ttl)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IncrementAndGet indicates an expected call of IncrementAndGet.
func (mr *MockPostgreSQLBackendMockRecorder) IncrementAndGet(ctx, key, ttl interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncrementAndGet", reflect.TypeOf((*MockPostgreSQLBackend)(nil).IncrementAndGet), ctx, key, ttl)
}

// Migrate mocks base method.
func (m *MockPostgreSQLBackend) Migrate(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Migrate", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Migrate indicates an expected call of Migrate.
func (mr *MockPostgreSQLBackendMockRecorder) Migrate(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Migrate", reflect.TypeOf((*MockPostgreSQLBackend)(nil).Migrate), ctx)
}

// Ping mocks base method.
func (m *MockPostgreSQLBackend) Ping(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ping", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Ping indicates an expected call of Ping.
func (mr *MockPostgreSQLBackendMockRecorder) Ping(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ping", reflect.TypeOf((*MockPostgreSQLBackend)(nil).Ping), ctx)
}

// Set mocks base method.
func (m *MockPostgreSQLBackend) Set(ctx context.Context, key string, state interface{}, ttl time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Set", ctx, key, state, ttl)
	ret0, _ := ret[0].(error)
	return ret0
}

// Set indicates an expected call of Set.
func (mr *MockPostgreSQLBackendMockRecorder) Set(ctx, key, state, ttl interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Set", reflect.TypeOf((*MockPostgreSQLBackend)(nil).Set), ctx, key, state, ttl)
}

// Transaction mocks base method.
func (m *MockPostgreSQLBackend) Transaction(ctx context.Context, fn func(backend.Backend) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Transaction", ctx, fn)
	ret0, _ := ret[0].(error)
	return ret0
}

// Transaction indicates an expected call of Transaction.
func (mr *MockPostgreSQLBackendMockRecorder) Transaction(ctx, fn interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Transaction", reflect.TypeOf((*MockPostgreSQLBackend)(nil).Transaction), ctx, fn)
}

// Type mocks base method.
func (m *MockPostgreSQLBackend) Type() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Type")
	ret0, _ := ret[0].(string)
	return ret0
}

// Type indicates an expected call of Type.
func (mr *MockPostgreSQLBackendMockRecorder) Type() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Type", reflect.TypeOf((*MockPostgreSQLBackend)(nil).Type))
}

// Vacuum mocks base method.
func (m *MockPostgreSQLBackend) Vacuum(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Vacuum", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Vacuum indicates an expected call of Vacuum.
func (mr *MockPostgreSQLBackendMockRecorder) Vacuum(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Vacuum", reflect.TypeOf((*MockPostgreSQLBackend)(nil).Vacuum), ctx)
}

// MockCustomBackend is a mock of CustomBackend interface.
type MockCustomBackend struct {
	ctrl     *gomock.Controller
	recorder *MockCustomBackendMockRecorder
}

// MockCustomBackendMockRecorder is the mock recorder for MockCustomBackend.
type MockCustomBackendMockRecorder struct {
	mock *MockCustomBackend
}

// NewMockCustomBackend creates a new mock instance.
func NewMockCustomBackend(ctrl *gomock.Controller) *MockCustomBackend {
	mock := &MockCustomBackend{ctrl: ctrl}
	mock.recorder = &MockCustomBackendMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCustomBackend) EXPECT() *MockCustomBackendMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockCustomBackend) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockCustomBackendMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockCustomBackend)(nil).Close))
}

// Delete mocks base method.
func (m *MockCustomBackend) Delete(ctx context.Context, key string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, key)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockCustomBackendMockRecorder) Delete(ctx, key interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockCustomBackend)(nil).Delete), ctx, key)
}

// Execute mocks base method.
func (m *MockCustomBackend) Execute(ctx context.Context, operation string, args map[string]interface{}) (interface{}, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, operation, args)
	ret0, _ := ret[0].(interface{})
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockCustomBackendMockRecorder) Execute(ctx, operation, args interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockCustomBackend)(nil).Execute), ctx, operation, args)
}

// Get mocks base method.
func (m *MockCustomBackend) Get(ctx context.Context, key string) (interface{}, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, key)
	ret0, _ := ret[0].(interface{})
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockCustomBackendMockRecorder) Get(ctx, key interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockCustomBackend)(nil).Get), ctx, key)
}

// GetMetadata mocks base method.
func (m *MockCustomBackend) GetMetadata(ctx context.Context) map[string]interface{} {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMetadata", ctx)
	ret0, _ := ret[0].(map[string]interface{})
	return ret0
}

// GetMetadata indicates an expected call of GetMetadata.
func (mr *MockCustomBackendMockRecorder) GetMetadata(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMetadata", reflect.TypeOf((*MockCustomBackend)(nil).GetMetadata), ctx)
}

// IncrementAndGet mocks base method.
func (m *MockCustomBackend) IncrementAndGet(ctx context.Context, key string, ttl time.Duration) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IncrementAndGet", ctx, key, ttl)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IncrementAndGet indicates an expected call of IncrementAndGet.
func (mr *MockCustomBackendMockRecorder) IncrementAndGet(ctx, key, ttl interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncrementAndGet", reflect.TypeOf((*MockCustomBackend)(nil).IncrementAndGet), ctx, key, ttl)
}

// Ping mocks base method.
func (m *MockCustomBackend) Ping(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ping", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Ping indicates an expected call of Ping.
func (mr *MockCustomBackendMockRecorder) Ping(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ping", reflect.TypeOf((*MockCustomBackend)(nil).Ping), ctx)
}

// Set mocks base method.
func (m *MockCustomBackend) Set(ctx context.Context, key string, state interface{}, ttl time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Set", ctx, key, state, ttl)
	ret0, _ := ret[0].(error)
	return ret0
}

// Set indicates an expected call of Set.
func (mr *MockCustomBackendMockRecorder) Set(ctx, key, state, ttl interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Set", reflect.TypeOf((*MockCustomBackend)(nil).Set), ctx, key, state, ttl)
}

// Type mocks base method.
func (m *MockCustomBackend) Type() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Type")
	ret0, _ := ret[0].(string)
	return ret0
}

// Type indicates an expected call of Type.
func (mr *MockCustomBackendMockRecorder) Type() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Type", reflect.TypeOf((*MockCustomBackend)(nil).Type))
}

// MockBackendFactory is a mock of BackendFactory interface.
type MockBackendFactory struct {
	ctrl     *gomock.Controller
	recorder *MockBackendFactoryMockRecorder
}

// MockBackendFactoryMockRecorder is the mock recorder for MockBackendFactory.
type MockBackendFactoryMockRecorder struct {
	mock *MockBackendFactory
}

// NewMockBackendFactory creates a new mock instance.
func NewMockBackendFactory(ctrl *gomock.Controller) *MockBackendFactory {
	mock := &MockBackendFactory{ctrl: ctrl}
	mock.recorder = &MockBackendFactoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBackendFactory) EXPECT() *MockBackendFactoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockBackendFactory) Create(config interface{}) (backend.Backend, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", config)
	ret0, _ := ret[0].(backend.Backend)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockBackendFactoryMockRecorder) Create(config interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockBackendFactory)(nil).Create), config)
}

// Type mocks base method.
func (m *MockBackendFactory) Type() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Type")
	ret0, _ := ret[0].(string)
	return ret0
}

// Type indicates an expected call of Type.
func (mr *MockBackendFactoryMockRecorder) Type() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Type", reflect.TypeOf((*MockBackendFactory)(nil).Type))
}

// MockBackendRegistry is a mock of BackendRegistry interface.
type MockBackendRegistry struct {
	ctrl     *gomock.Controller
	recorder *MockBackendRegistryMockRecorder
}

// MockBackendRegistryMockRecorder is the mock recorder for MockBackendRegistry.
type MockBackendRegistryMockRecorder struct {
	mock *MockBackendRegistry
}

// NewMockBackendRegistry creates a new mock instance.
func NewMockBackendRegistry(ctrl *gomock.Controller) *MockBackendRegistry {
	mock := &MockBackendRegistry{ctrl: ctrl}
	mock.recorder = &MockBackendRegistryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBackendRegistry) EXPECT() *MockBackendRegistryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockBackendRegistry) Create(backendType string, config interface{}) (backend.Backend, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", backendType, config)
	ret0, _ := ret[0].(backend.Backend)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockBackendRegistryMockRecorder) Create(backendType, config interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockBackendRegistry)(nil).Create), backendType, config)
}

// Get mocks base method.
func (m *MockBackendRegistry) Get(backendType string) (backend.BackendFactory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", backendType)
	ret0, _ := ret[0].(backend.BackendFactory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockBackendRegistryMockRecorder) Get(backendType interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockBackendRegistry)(nil).Get), backendType)
}

// List mocks base method.
func (m *MockBackendRegistry) List() []string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List")
	ret0, _ := ret[0].([]string)
	return ret0
}

// List indicates an expected call of List.
func (mr *MockBackendRegistryMockRecorder) List() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockBackendRegistry)(nil).List))
}

// Register mocks base method.
func (m *MockBackendRegistry) Register(factory backend.BackendFactory) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Register", factory)
	ret0, _ := ret[0].(error)
	return ret0
}

// Register indicates an expected call of Register.
func (mr *MockBackendRegistryMockRecorder) Register(factory interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Register", reflect.TypeOf((*MockBackendRegistry)(nil).Register), factory)
}
