// Code generated by MockGen. DO NOT EDIT.
// Source: features/dynamic_limits.go

// Package mocks is a generated GoMock package.
package mocks

import (
	"context"
	"reflect"
	"time"

	gomock "github.com/golang/mock/gomock"
)

// MockDynamicLimitController is a mock of DynamicLimitController interface.
type MockDynamicLimitController struct {
	ctrl     *gomock.Controller
	recorder *MockDynamicLimitControllerMockRecorder
}

// MockDynamicLimitControllerMockRecorder is the mock recorder for MockDynamicLimitController.
type MockDynamicLimitControllerMockRecorder struct {
	mock *MockDynamicLimitController
}

// NewMockDynamicLimitController creates a new mock instance.
func NewMockDynamicLimitController(ctrl *gomock.Controller) *MockDynamicLimitController {
	mock := &MockDynamicLimitController{ctrl: ctrl}
	mock.recorder = &MockDynamicLimitControllerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDynamicLimitController) EXPECT() *MockDynamicLimitControllerMockRecorder {
	return m.recorder
}

// UpdateLimit mocks base method.
func (m *MockDynamicLimitController) UpdateLimit(ctx context.Context, key string, newLimit int, window time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateLimit", ctx, key, newLimit, window)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateLimit indicates an expected call of UpdateLimit.
func (mr *MockDynamicLimitControllerMockRecorder) UpdateLimit(ctx, key, newLimit, window interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateLimit", reflect.TypeOf((*MockDynamicLimitController)(nil).UpdateLimit), ctx, key, newLimit, window)
}

// UpdateLimitByTier mocks base method.
func (m *MockDynamicLimitController) UpdateLimitByTier(ctx context.Context, tier string, newLimit int, window time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateLimitByTier", ctx, tier, newLimit, window)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateLimitByTier indicates an expected call of UpdateLimitByTier.
func (mr *MockDynamicLimitControllerMockRecorder) UpdateLimitByTier(ctx, tier, newLimit, window interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateLimitByTier", reflect.TypeOf((*MockDynamicLimitController)(nil).UpdateLimitByTier), ctx, tier, newLimit, window)
}

// UpdateLimitByTenant mocks base method.
func (m *MockDynamicLimitController) UpdateLimitByTenant(ctx context.Context, tenantID string, newLimit int, window time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateLimitByTenant", ctx, tenantID, newLimit, window)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateLimitByTenant indicates an expected call of UpdateLimitByTenant.
func (mr *MockDynamicLimitControllerMockRecorder) UpdateLimitByTenant(ctx, tenantID, newLimit, window interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateLimitByTenant", reflect.TypeOf((*MockDynamicLimitController)(nil).UpdateLimitByTenant), ctx, tenantID, newLimit, window)
}

// GetCurrentLimit mocks base method.
func (m *MockDynamicLimitController) GetCurrentLimit(ctx context.Context, key string) (int, time.Duration, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCurrentLimit", ctx, key)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(time.Duration)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetCurrentLimit indicates an expected call of GetCurrentLimit.
func (mr *MockDynamicLimitControllerMockRecorder) GetCurrentLimit(ctx, key interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCurrentLimit", reflect.TypeOf((*MockDynamicLimitController)(nil).GetCurrentLimit), ctx, key)
}

// ReloadConfig mocks base method.
func (m *MockDynamicLimitController) ReloadConfig(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReloadConfig", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReloadConfig indicates an expected call of ReloadConfig.
func (mr *MockDynamicLimitControllerMockRecorder) ReloadConfig(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReloadConfig", reflect.TypeOf((*MockDynamicLimitController)(nil).ReloadConfig), ctx)
}
