// Code generated by MockGen. DO NOT EDIT.
// Source: observability/tracing/tracer.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	obstypes "github.com/abhipray-cpu/niyantrak/observability/types"
	gomock "github.com/golang/mock/gomock"
)

// MockTracer is a mock of Tracer interface.
type MockTracer struct {
	ctrl     *gomock.Controller
	recorder *MockTracerMockRecorder
}

// MockTracerMockRecorder is the mock recorder for MockTracer.
type MockTracerMockRecorder struct {
	mock *MockTracer
}

// NewMockTracer creates a new mock instance.
func NewMockTracer(ctrl *gomock.Controller) *MockTracer {
	mock := &MockTracer{ctrl: ctrl}
	mock.recorder = &MockTracerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTracer) EXPECT() *MockTracerMockRecorder {
	return m.recorder
}

// AddAttribute mocks base method.
func (m *MockTracer) AddAttribute(span *obstypes.SpanContext, key string, value interface{}) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddAttribute", span, key, value)
}

// AddAttribute indicates an expected call of AddAttribute.
func (mr *MockTracerMockRecorder) AddAttribute(span, key, value interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddAttribute", reflect.TypeOf((*MockTracer)(nil).AddAttribute), span, key, value)
}

// AddEvent mocks base method.
func (m *MockTracer) AddEvent(span *obstypes.SpanContext, event string, args ...interface{}) {
	m.ctrl.T.Helper()
	varargs := []interface{}{span, event}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "AddEvent", varargs...)
}

// AddEvent indicates an expected call of AddEvent.
func (mr *MockTracerMockRecorder) AddEvent(span, event interface{}, args ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{span, event}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddEvent", reflect.TypeOf((*MockTracer)(nil).AddEvent), varargs...)
}

// EndSpan mocks base method.
func (m *MockTracer) EndSpan(span *obstypes.SpanContext) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "EndSpan", span)
}

// EndSpan indicates an expected call of EndSpan.
func (mr *MockTracerMockRecorder) EndSpan(span interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EndSpan", reflect.TypeOf((*MockTracer)(nil).EndSpan), span)
}

// SetError mocks base method.
func (m *MockTracer) SetError(span *obstypes.SpanContext, message string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetError", span, message)
}

// SetError indicates an expected call of SetError.
func (mr *MockTracerMockRecorder) SetError(span, message interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetError", reflect.TypeOf((*MockTracer)(nil).SetError), span, message)
}

// StartSpan mocks base method.
func (m *MockTracer) StartSpan(ctx context.Context, name string) *obstypes.SpanContext {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StartSpan", ctx, name)
	ret0, _ := ret[0].(*obstypes.SpanContext)
	return ret0
}

// StartSpan indicates an expected call of StartSpan.
func (mr *MockTracerMockRecorder) StartSpan(ctx, name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartSpan", reflect.TypeOf((*MockTracer)(nil).StartSpan), ctx, name)
}
