// Code generated by MockGen. DO NOT EDIT.
// Source: algorithm/interfaces.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	algorithm "github.com/abhipray-cpu/niyantrak/algorithm"
	gomock "github.com/golang/mock/gomock"
)

// MockAlgorithm is a mock of Algorithm interface.
type MockAlgorithm struct {
	ctrl     *gomock.Controller
	recorder *MockAlgorithmMockRecorder
}

// MockAlgorithmMockRecorder is the mock recorder for MockAlgorithm.
type MockAlgorithmMockRecorder struct {
	mock *MockAlgorithm
}

// NewMockAlgorithm creates a new mock instance.
func NewMockAlgorithm(ctrl *gomock.Controller) *MockAlgorithm {
	mock := &MockAlgorithm{ctrl: ctrl}
	mock.recorder = &MockAlgorithmMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAlgorithm) EXPECT() *MockAlgorithmMockRecorder {
	return m.recorder
}

// Allow mocks base method.
func (m *MockAlgorithm) Allow(ctx context.Context, state interface{}, cost int) (interface{}, interface{}, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Allow", ctx, state, cost)
	ret0, _ := ret[0].(interface{})
	ret1, _ := ret[1].(interface{})
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Allow indicates an expected call of Allow.
func (mr *MockAlgorithmMockRecorder) Allow(ctx, state, cost interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Allow", reflect.TypeOf((*MockAlgorithm)(nil).Allow), ctx, state, cost)
}

// Description mocks base method.
func (m *MockAlgorithm) Description() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Description")
	ret0, _ := ret[0].(string)
	return ret0
}

// Description indicates an expected call of Description.
func (mr *MockAlgorithmMockRecorder) Description() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Description", reflect.TypeOf((*MockAlgorithm)(nil).Description))
}

// GetStats mocks base method.
func (m *MockAlgorithm) GetStats(ctx context.Context, state interface{}) interface{} {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStats", ctx, state)
	ret0, _ := ret[0].(interface{})
	return ret0
}

// GetStats indicates an expected call of GetStats.
func (mr *MockAlgorithmMockRecorder) GetStats(ctx, state interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStats", reflect.TypeOf((*MockAlgorithm)(nil).GetStats), ctx, state)
}

// Name mocks base method.
func (m *MockAlgorithm) Name() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Name")
	ret0, _ := ret[0].(string)
	return ret0
}

// Name indicates an expected call of Name.
func (mr *MockAlgorithmMockRecorder) Name() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Name", reflect.TypeOf((*MockAlgorithm)(nil).Name))
}

// Reset mocks base method.
func (m *MockAlgorithm) Reset(ctx context.Context) (interface{}, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Reset", ctx)
	ret0, _ := ret[0].(interface{})
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Reset indicates an expected call of Reset.
func (mr *MockAlgorithmMockRecorder) Reset(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Reset", reflect.TypeOf((*MockAlgorithm)(nil).Reset), ctx)
}

// ValidateConfig mocks base method.
func (m *MockAlgorithm) ValidateConfig(config interface{}) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateConfig", config)
	ret0, _ := ret[0].(error)
	return ret0
}

// ValidateConfig indicates an expected call of ValidateConfig.
func (mr *MockAlgorithmMockRecorder) ValidateConfig(config interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateConfig", reflect.TypeOf((*MockAlgorithm)(nil).ValidateConfig), config)
}

// MockAlgorithmFactory is a mock of AlgorithmFactory interface.
type MockAlgorithmFactory struct {
	ctrl     *gomock.Controller
	recorder *MockAlgorithmFactoryMockRecorder
}

// MockAlgorithmFactoryMockRecorder is the mock recorder for MockAlgorithmFactory.
type MockAlgorithmFactoryMockRecorder struct {
	mock *MockAlgorithmFactory
}

// NewMockAlgorithmFactory creates a new mock instance.
func NewMockAlgorithmFactory(ctrl *gomock.Controller) *MockAlgorithmFactory {
	mock := &MockAlgorithmFactory{ctrl: ctrl}
	mock.recorder = &MockAlgorithmFactoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAlgorithmFactory) EXPECT() *MockAlgorithmFactoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockAlgorithmFactory) Create(config interface{}) (algorithm.Algorithm, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", config)
	ret0, _ := ret[0].(algorithm.Algorithm)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockAlgorithmFactoryMockRecorder) Create(config interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockAlgorithmFactory)(nil).Create), config)
}

// Type mocks base method.
func (m *MockAlgorithmFactory) Type() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Type")
	ret0, _ := ret[0].(string)
	return ret0
}

// Type indicates an expected call of Type.
func (mr *MockAlgorithmFactoryMockRecorder) Type() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Type", reflect.TypeOf((*MockAlgorithmFactory)(nil).Type))
}

// MockAlgorithmRegistry is a mock of AlgorithmRegistry interface.
type MockAlgorithmRegistry struct {
	ctrl     *gomock.Controller
	recorder *MockAlgorithmRegistryMockRecorder
}

// MockAlgorithmRegistryMockRecorder is the mock recorder for MockAlgorithmRegistry.
type MockAlgorithmRegistryMockRecorder struct {
	mock *MockAlgorithmRegistry
}

// NewMockAlgorithmRegistry creates a new mock instance.
func NewMockAlgorithmRegistry(ctrl *gomock.Controller) *MockAlgorithmRegistry {
	mock := &MockAlgorithmRegistry{ctrl: ctrl}
	mock.recorder = &MockAlgorithmRegistryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAlgorithmRegistry) EXPECT() *MockAlgorithmRegistryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockAlgorithmRegistry) Create(algorithmType string, config interface{}) (algorithm.Algorithm, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", algorithmType, config)
	ret0, _ := ret[0].(algorithm.Algorithm)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockAlgorithmRegistryMockRecorder) Create(algorithmType, config interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockAlgorithmRegistry)(nil).Create), algorithmType, config)
}

// Get mocks base method.
func (m *MockAlgorithmRegistry) Get(algorithmType string) (algorithm.AlgorithmFactory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", algorithmType)
	ret0, _ := ret[0].(algorithm.AlgorithmFactory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockAlgorithmRegistryMockRecorder) Get(algorithmType interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockAlgorithmRegistry)(nil).Get), algorithmType)
}

// List mocks base method.
func (m *MockAlgorithmRegistry) List() []string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List")
	ret0, _ := ret[0].([]string)
	return ret0
}

// List indicates an expected call of List.
func (mr *MockAlgorithmRegistryMockRecorder) List() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockAlgorithmRegistry)(nil).List))
}

// Register mocks base method.
func (m *MockAlgorithmRegistry) Register(factory algorithm.AlgorithmFactory) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Register", factory)
	ret0, _ := ret[0].(error)
	return ret0
}

// Register indicates an expected call of Register.
func (mr *MockAlgorithmRegistryMockRecorder) Register(factory interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Register", reflect.TypeOf((*MockAlgorithmRegistry)(nil).Register), factory)
}
