// Code generated by MockGen. DO NOT EDIT.
// Source: observability/metrics/metrics.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockMetrics is a mock of Metrics interface.
type MockMetrics struct {
	ctrl     *gomock.Controller
	recorder *MockMetricsMockRecorder
}

// MockMetricsMockRecorder is the mock recorder for MockMetrics.
type MockMetricsMockRecorder struct {
	mock *MockMetrics
}

// NewMockMetrics creates a new mock instance.
func NewMockMetrics(ctrl *gomock.Controller) *MockMetrics {
	mock := &MockMetrics{ctrl: ctrl}
	mock.recorder = &MockMetricsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMetrics) EXPECT() *MockMetricsMockRecorder {
	return m.recorder
}

// GetMetrics mocks base method.
func (m *MockMetrics) GetMetrics() interface{} {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMetrics")
	ret0, _ := ret[0].(interface{})
	return ret0
}

// GetMetrics indicates an expected call of GetMetrics.
func (mr *MockMetricsMockRecorder) GetMetrics() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMetrics", reflect.TypeOf((*MockMetrics)(nil).GetMetrics))
}

// RecordDecisionLatency mocks base method.
func (m *MockMetrics) RecordDecisionLatency(key string, latencyNs int64) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RecordDecisionLatency", key, latencyNs)
}

// RecordDecisionLatency indicates an expected call of RecordDecisionLatency.
func (mr *MockMetricsMockRecorder) RecordDecisionLatency(key, latencyNs interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordDecisionLatency", reflect.TypeOf((*MockMetrics)(nil).RecordDecisionLatency), key, latencyNs)
}

// RecordRequest mocks base method.
func (m *MockMetrics) RecordRequest(key string, allowed bool, limit int64) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RecordRequest", key, allowed, limit)
}

// RecordRequest indicates an expected call of RecordRequest.
func (mr *MockMetricsMockRecorder) RecordRequest(key, allowed, limit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordRequest", reflect.TypeOf((*MockMetrics)(nil).RecordRequest), key, allowed, limit)
}
